#!/usr/bin/env python3
"""Check commit subjects / PR titles against Conventional Commits — standard library only.

Releases are derived from these subjects (python-semantic-release): ``feat`` -> minor,
``fix``/``perf`` -> patch, ``!`` or a ``BREAKING CHANGE:`` footer -> major; the other types
release nothing. Used by the ``commit-msg`` pre-commit hook and the CI ``commits`` job.

    check_commits.py --message-file .git/COMMIT_EDITMSG
    check_commits.py --title "feat(executor): ..." --range BASE..HEAD
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

TYPES = (
    "build",
    "chore",
    "ci",
    "docs",
    "feat",
    "fix",
    "perf",
    "refactor",
    "revert",
    "style",
    "test",
)
MAX_LENGTH = 100

_SUBJECT = re.compile(rf"^(?:{'|'.join(TYPES)})(?:\([\w./,-]+\))?!?: \S")
# Commit subjects generated by git / GitHub; they never trigger a release. Only exact generated
# forms, and never for a PR title, which becomes the squash commit's subject.
_GENERATED = re.compile(
    r"^(?:Merge (?:branch|remote-tracking branch) '[^']+'"
    r"|Merge pull request #\d+ from \S+"
    r'|Revert ".+")'
)


def problem(subject: str, *, allow_generated: bool = True) -> str | None:
    """Why ``subject`` is not a valid commit subject, or ``None``."""
    if allow_generated and _GENERATED.match(subject):
        return None
    if len(subject) > MAX_LENGTH:
        return f"longer than {MAX_LENGTH} characters"
    if not _SUBJECT.match(subject):
        if subject.startswith('Revert "'):
            # GitHub's revert button titles the PR like this; the squash commit needs a type.
            return f"use 'revert: {subject.removeprefix('Revert ').strip(chr(34))}' instead"
        return f"expected '<type>[(scope)][!]: <description>' with type one of {', '.join(TYPES)}"
    return None


def subject_of_message(message: str) -> str:
    """First line of a commit message, ignoring git's ``#`` comment lines."""
    for line in message.splitlines():
        if line.strip() and not line.startswith("#"):
            return line.rstrip()
    return ""


def _range_subjects(rev_range: str) -> list[str]:
    out = subprocess.run(
        ["git", "log", "--format=%s", rev_range], check=True, capture_output=True, text=True
    )
    return out.stdout.splitlines()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--message-file", type=Path, help="commit message file (commit-msg hook)")
    parser.add_argument("--title", help="pull request title")
    parser.add_argument("--range", dest="rev_range", help="git revision range, e.g. BASE..HEAD")
    args = parser.parse_args(argv)

    subjects: list[tuple[str, str]] = []
    if args.message_file:
        text = args.message_file.read_text(encoding="utf-8")
        subjects.append(("commit message", subject_of_message(text)))
    if args.title is not None:
        subjects.append(("PR title", args.title))
    if args.rev_range:
        subjects += [("commit", s) for s in _range_subjects(args.rev_range)]
    if not subjects:
        parser.error("nothing to check")

    failures = [
        (kind, s, why)
        for kind, s in subjects
        if (why := problem(s, allow_generated=kind != "PR title")) is not None
    ]
    for kind, subject, why in failures:
        print(f"{kind} {subject!r}: {why}", file=sys.stderr)
    if failures:
        print(
            "See https://www.conventionalcommits.org/ and README.md "
            "('Commit messages and versioning').",
            file=sys.stderr,
        )
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
